### ISSUE TITLE
Possibility to set Major ticks to rounded values

### ISSUE THREAD

**Issue by ErikWahlstrom** [GuOrg/Gu.Wpf.Gauges#24]
Right now the major tick will end up depending on what the min-value is set to (e.g. 1.3 2.3 4.3)

**Comment by JohanLarsson** [comment]
I'm thinking `SnapTicksTo="TickFrequency"`

```c#
enum TickSnap
{
    TickFrequency,
    Minimum,
    Maximum,
}
```
